# Generated by Django 4.0.1 on 2022-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_string', models.CharField(max_length=200)),
                ('find_type', models.CharField(max_length=10)),
                ('row_number', models.IntegerField()),
                ('tail_number', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('type_name', models.TextField()),
                ('year_of_production', models.CharField(max_length=4)),
                ('images', models.JSONField()),
                ('class_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('home_base', models.CharField(max_length=200)),
            ],
        ),
    ]
