# Generated by Django 4.0.1 on 2022-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviapages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='class_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='company_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='home_base',
            field=models.TextField(),
        ),
    ]
