# Generated by Django 4.0.1 on 2022-02-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviapages', '0002_alter_aircraftdata_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftdata',
            name='class_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='home_base',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='images',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='serial_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='tail_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='type_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraftdata',
            name='year_of_production',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
