# Generated by Django 4.0.1 on 2022-02-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviapages', '0003_alter_aircraftdata_class_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AircraftData',
        ),
    ]
